import type { FonteResposta, Vaga } from "./vagas-types";

// Dados de exemplo estruturais.
// A lógica real de parsing (Sine/SETEMP) deve substituir estes stubs
// mantendo exatamente o mesmo contrato (Vaga[]).

const HOJE = new Date().toISOString().slice(0, 10);

const vagasSine: Vaga[] = [
  {
    id: "sine-001",
    slug: "auxiliar-de-producao-distrito-industrial",
    titulo: "Auxiliar de Produção",
    empresa: "Indústria do Polo Industrial",
    cidade: "Manaus",
    estado: "AM",
    bairro: "Distrito Industrial I",
    categoria: "Produção",
    escolaridade: "Ensino Médio Completo",
    experiencia: "Não exigida",
    salario: "Não informado",
    requisitos: ["Disponibilidade para turnos rotativos", "Residir em Manaus"],
    beneficios: ["Vale-transporte", "Vale-alimentação", "Plano de saúde"],
    comoSeCandidatar:
      "Comparecer a qualquer posto do Sine Manaus com documentos pessoais e currículo impresso.",
    fonte: "Prefeitura de Manaus - Sine Manaus",
    linkFonte: "https://www.manaus.am.gov.br/",
    dataPublicacao: HOJE,
    status: "aberta",
    tipoContrato: "CLT",
    modalidade: "Presencial",
    quantidadeVagas: 12,
    pcd: false,
  },
  {
    id: "sine-002",
    slug: "operador-de-caixa-shopping",
    titulo: "Operador de Caixa",
    empresa: "Rede de Supermercados",
    cidade: "Manaus",
    estado: "AM",
    bairro: "Adrianópolis",
    categoria: "Comércio",
    escolaridade: "Ensino Médio Completo",
    experiencia: "6 meses",
    salario: "Não informado",
    requisitos: ["Boa comunicação", "Experiência com atendimento"],
    beneficios: ["Vale-transporte", "Refeição no local"],
    comoSeCandidatar: "Candidatura presencial em qualquer posto do Sine Manaus.",
    fonte: "Prefeitura de Manaus - Sine Manaus",
    linkFonte: "https://www.manaus.am.gov.br/",
    dataPublicacao: HOJE,
    status: "aberta",
    tipoContrato: "CLT",
    modalidade: "Presencial",
    quantidadeVagas: 3,
    pcd: true,
  },
  {
    id: "sine-003",
    slug: "auxiliar-de-limpeza-centro",
    titulo: "Auxiliar de Serviços Gerais",
    empresa: "Empresa de Facilities",
    cidade: "Manaus",
    estado: "AM",
    bairro: "Centro",
    categoria: "Serviços Gerais",
    escolaridade: "Ensino Fundamental",
    experiencia: "Não exigida",
    salario: "Não informado",
    requisitos: ["Disponibilidade de horário"],
    beneficios: ["Vale-transporte", "Vale-alimentação"],
    comoSeCandidatar: "Comparecer ao posto do Sine Manaus mais próximo.",
    fonte: "Prefeitura de Manaus - Sine Manaus",
    linkFonte: "https://www.manaus.am.gov.br/",
    dataPublicacao: HOJE,
    status: "aberta",
    tipoContrato: "CLT",
    modalidade: "Presencial",
    quantidadeVagas: 8,
    pcd: false,
  },
];

const vagasSetemp: Vaga[] = [
  {
    id: "setemp-001",
    slug: "conferente-de-cargas-taruma",
    titulo: "Conferente de Cargas",
    empresa: "Transportadora AM",
    cidade: "Manaus",
    estado: "AM",
    bairro: "Tarumã",
    categoria: "Logística",
    escolaridade: "Ensino Médio Completo",
    experiencia: "6 meses",
    salario: "R$ 1.840,00",
    requisitos: ["Conhecimento básico em informática"],
    beneficios: ["Vale-transporte", "Vale-refeição"],
    comoSeCandidatar: "Candidatar-se pelo Portal do Trabalhador do Amazonas.",
    fonte: "SETEMP - Portal do Trabalhador do Amazonas",
    linkFonte: "https://portaldotrabalhador.setemp.am.gov.br/",
    dataPublicacao: HOJE,
    status: "aberta",
    tipoContrato: "Efetivo",
    modalidade: "Presencial",
    quantidadeVagas: 2,
    pcd: false,
  },
  {
    id: "setemp-002",
    slug: "assistente-administrativo-parque-dez",
    titulo: "Assistente Administrativo",
    empresa: "Escritório Contábil",
    cidade: "Manaus",
    estado: "AM",
    bairro: "Parque 10 de Novembro",
    categoria: "Administrativo",
    escolaridade: "Ensino Médio Completo",
    experiencia: "1 ano",
    salario: "R$ 1.600,00",
    requisitos: ["Pacote Office", "Boa comunicação escrita"],
    beneficios: ["Vale-transporte", "Vale-refeição", "Plano odontológico"],
    comoSeCandidatar: "Cadastro e candidatura online no Portal do Trabalhador.",
    fonte: "SETEMP - Portal do Trabalhador do Amazonas",
    linkFonte: "https://portaldotrabalhador.setemp.am.gov.br/",
    dataPublicacao: HOJE,
    status: "aberta",
    tipoContrato: "CLT",
    modalidade: "Presencial",
    quantidadeVagas: 1,
    pcd: false,
  },
];

export const mockRespostaSine: FonteResposta = {
  vagas: vagasSine,
  resumo: {
    fonte: "Prefeitura de Manaus - Sine Manaus",
    totalCargos: vagasSine.length,
    totalVagas: vagasSine.reduce((acc, v) => acc + (v.quantidadeVagas ?? 1), 0),
    linkOficial: "https://www.manaus.am.gov.br/",
    atualizadoEm: new Date().toISOString(),
  },
};

export const mockRespostaSetemp: FonteResposta = {
  vagas: vagasSetemp,
  resumo: {
    fonte: "SETEMP - Portal do Trabalhador do Amazonas",
    totalCargos: vagasSetemp.length,
    totalVagas: vagasSetemp.reduce((acc, v) => acc + (v.quantidadeVagas ?? 1), 0),
    linkOficial: "https://portaldotrabalhador.setemp.am.gov.br/",
    atualizadoEm: new Date().toISOString(),
  },
};
